### ISSUE TITLE
add option for decode AndroidManifest.xml

### ISSUE THREAD

**Issue by remo7777** [Lexiie/Termux-Apktool#1]
**AndroidManifest.xml encrypted** 
we need to change or modify AndroidManifest.xml
but here that file fully encrypted state
**add option for decrypt AndroidManifest**
and its for all sdk version i think
you hv set 24 only

**Comment by Lexiie** [comment]
I set to min sdk 21 
This tools cannot fully decrypt cause built in binary aapt used linux system 32/64 not arm 
I think you can replace with your spesific architecture cause termux have aapt package 
Sorry for bad english
