### ISSUE TITLE
Failed to initialize runtime (check log for details)

### ISSUE THREAD

**Issue by Cvar1984** [Lexiie/Termux-Apktool#2]
read(10, "#!/usr/bin/sh\n\nsdk=$(getprop ro."..., 1024) = 279
rt_sigprocmask(0xe965f668 /* SIG_??? */, NULL, [], 8) = 0
pipe2([3, 4], 0)                        = 0
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7faa596ab0) = 7050
close(4)                                = 0
read(3, "25\n", 128)                    = 3
read(3, "", 128)                        = 0
close(3)                                = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 7050
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=7050, si_uid=10115, si_status=0, si_utime=2, si_stime=1} ---
rt_sigreturn({mask=[]})                 = 7050
rt_sigprocmask(0xe965f650 /* SIG_??? */, NULL, [], 8) = 0
wait4(-1, 0x7fe965f6fc, WNOHANG, NULL)  = -1 ECHILD (No child processes)
rt_sigprocmask(0xe965f628 /* SIG_??? */, NULL, [], 8) = 0
rt_sigprocmask(0xe965f610 /* SIG_??? */, NULL, [], 8) = 0
rt_sigprocmask(0xe965f668 /* SIG_??? */, NULL, [], 8) = 0
newfstatat(AT_FDCWD, "/data/data/com.termux/files/home/.local/bin/dalvikvm", 0x7fe965f6c8, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/data/data/com.termux/files/usr/bin/dalvikvm", {st_dev=makedev(0xfd, 0x1), st_ino=148347, st_mode=S_IFREG|0700, st_nlink=1, st_uid=10115, st_gid=10115, st_blksize=4096, st_blocks=8, st_size=320, st_atime=1571183913 /* 2019-10-16T06:58:33+0700 */, st_atime_nsec=0, st_mtime=1570348946 /* 2019-10-06T15:02:26+0700 */, st_mtime_nsec=0, st_ctime=1571183913 /* 2019-10-16T06:58:33.607532833+0700 */, st_ctime_nsec=607532833}, 0) = 0
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7faa596ab0) = 7051
wait4(-1, Failed to initialize runtime (check log for details)
[{WIFEXITED(s) && WEXITSTATUS(s) == 1}], 0, NULL) = 7051
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=7051, si_uid=10115, si_status=1, si_utime=2, si_stime=2} ---
rt_sigreturn({mask=[]})                 = 7051                                          read(10, "", 1024)                      = 0
rt_sigprocmask(0xe965f840 /* SIG_??? */, NULL, [], 8) = 0
rt_sigprocmask(0xe965f840 /* SIG_??? */, NULL, [], 8) = 0
exit_group(1)                           = ?
+++ exited with 1 +++

ini ga support aarch64?

**Comment by Lexiie** [comment]
Bug nougat 
sed -i 's/export/#export/g; s/mkdir/#mkdir/g' $PREFIX/bin/dalvikvm
